---
title: "EDA"
output:
  html_document:
    df_print: paged
---

# Import pkgs 

```{r}
# Import pkgs
pacman::p_load(
  tidyverse,
  lubridate, 
  purrr,
  furrr,
  tm,
  quanteda, 
  here,
  tidytext, # text analysis 
  ggthemes,
  text2vec, # word embedding 
  widyr,
  patchwork, # arranging ggplots
  glue,
  # deep learning 
  text2vec,
  # network graph
  igraph,
  ggraph,
  # structural breakpoint
  strucchange,
  pbapply
)

devtools::install_github("prodriguezsosa/conText")
library(conText)
theme_set(theme_clean())

source(here("functions", "utils.r"))
```

# Import files 

```{r}
load(file = here("processed_data/processed_text.Rdata"))

# Remove unnecessary files 
rm(list = ls()[grep("tf_idf", ls())])

asian_text <- asian_text %>%
  select(date, value, source)
asian_text$year <- year(asian_text$date)

df$source <- "NCLR"
df$year <- year(df$date)

yrs <- intersect(df$year, asian_text$year)

corpus <- bind_rows(
  filter(df, year %in% yrs), 
  filter(asian_text, year %in% yrs))

names(corpus)

corpus$latino <- if_else(corpus$source == "NCLR", 1L, 0L)
```

# Word embedding

## Local embedding and matrix 

```{r}
local_glove <- df2vec(corpus)
fcm_cr <- df2cm(corpus)
local_transform <- df2ltm(corpus, fcm_cr, local_glove)

save(local_glove, local_transform, 
     file = here("processed_data/context_bg.Rdata"))
```
 
## ALC embedding approach 

### Dynamic 

```{r}
# Thanks Pedro L. Rodríguez for sharing his code. 

# run regression for each period and user inner product

models_black <- pblapply(
  unique(corpus$year), function(j){ conText(formula = black ~ latino, 
          data = corpus[corpus$year == j,], 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)
  })

models_disc <- pblapply(
  unique(corpus$year), function(j){ conText(formula = discrimination ~ latino, 
          data = corpus[corpus$year == j,], 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)
  })

models_minority <- pblapply(
  unique(corpus$year), function(j){ conText(formula = minority ~ latino, 
          data = corpus[corpus$year == j,], 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)
  })

models_federal <- pblapply(
  unique(corpus$year), function(j){ conText(formula = federal ~ latino, 
          data = corpus[corpus$year == j,], 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)
  })
```

```{r}
(models2plot_seq(models_black, "Black") + ylim(c(0, 2.5))) +
(models2plot_seq(models_disc, "Discrimination") + ylim(c(0, 2.5))) 

ggsave(here("outputs", "ts_embed_plot.png"))
```

```{r}
corpus$post <- if_else(corpus$year >= 1976, 1, 0) 
```

### Regression 

```{r}
mod_black <- conText(formula = black ~ latino + post, 
          data = corpus, 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)

mod_disc <- conText(formula = discrimination ~ latino + post, 
          data = corpus, 
          text_var = 'value', 
          pre_trained = local_glove,
          transform = TRUE, 
          transform_matrix = local_transform, 
          bootstrap = TRUE, 
          num_bootstraps = 20, 
          stratify_by = c('latino'), 
          permute = TRUE, 
          num_permutations = 100, 
          window = 6, 
          valuetype = 'fixed', 
          case_insensitive = TRUE, 
          hard_cut = FALSE, 
          verbose = FALSE)
```

```{r}
plot_tibble_black <- mod_black$normed_betas %>% 
  mutate(Coefficient = c("Latino", "Post-1976")) %>% 
  mutate(Coefficient = factor(Coefficient, levels = Coefficient))

plot_tibble_disc <- mod_disc$normed_betas %>% 
  mutate(Coefficient = c("Latino", "Post-1976")) %>% 
  mutate(Coefficient = factor(Coefficient, levels = Coefficient))
```

```{r}
reg_blk_plot <- plot_tibble_black %>%
  ggplot(aes(x = Coefficient, y = Normed_Estimate)) + 
  geom_bar(position = position_dodge(), 
    stat = "identity", width = 0.5) + 
  geom_errorbar(aes(ymin = Normed_Estimate - 
    1.96 * Std.Error, ymax = Normed_Estimate + 1.96 * Std.Error), size = 0.75, width = 0.15, 
    position = position_dodge(0.9)) + 
  ylab("Norm of beta hats") + 
  geom_text(aes(label = c("***", "*")), position = position_dodge(width = 0.9), hjust = 0.5, vjust = -1, size = 8) + 
  theme(axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
          axis.text.y = element_text(size = 10)) +
  ylim(c(0,1.4)) +
  labs(title = "Keyword: Black")

reg_disc_plot <- plot_tibble_disc %>%
  ggplot(aes(x = Coefficient, y = Normed_Estimate)) + 
  geom_bar(position = position_dodge(), 
    stat = "identity", width = 0.5) + 
  geom_errorbar(aes(ymin = Normed_Estimate - 
    1.96 * Std.Error, ymax = Normed_Estimate + 1.96 * Std.Error), size = 0.75, width = 0.15, 
    position = position_dodge(0.9)) + 
  ylab("Norm of beta hats") + 
  geom_text(aes(label = c("***", "")), position = position_dodge(width = 0.9), hjust = 0.5, vjust = -1, size = 8) + 
  theme(axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
          axis.text.y = element_text(size = 10)) +
  ylim(c(0,1.4)) +
  labs(title = "Keyword: Discrimination")

reg_blk_plot + reg_disc_plot
ggsave(here("outputs", "embed_reg_combined.png"))
```

## Nearest neighbors 

### ALC embedding 

```{r}
latino_pre_black_bt <- get_bt_terms(1, 0, "black", 200)
asian_pre_black_bt <- get_bt_terms(0, 0, "black", 200)

latino_post_black_bt <- get_bt_terms(1, 1, "black", 200)
asian_post_black_bt <- get_bt_terms(0, 1, "black", 200)

latino_pre_disc_bt <- get_bt_terms(1, 0, "discrimination", 200)
asian_pre_disc_bt <- get_bt_terms(0, 0, "discrimination", 200)

latino_post_disc_bt <- get_bt_terms(1, 1, "discrimination", 200)
asian_post_disc_bt <- get_bt_terms(0, 1, "discrimination", 200)

latino_pre_compared_bt <- get_bt_terms(1, 0, "compared", 200)
asian_pre_compared_bt <- get_bt_terms(0, 0, "compared", 200)

latino_post_compared_bt <- get_bt_terms(1, 1, "compared", 200)
asian_post_compared_bt <- get_bt_terms(0, 1, "compared", 200)
```

```{r}
terms2plot(latino_pre_disc_bt, asian_pre_disc_bt, "Discrimination", "Pre-1976") + terms2plot(latino_post_disc_bt, asian_post_disc_bt, "Discrimination", "Post-1976")

ggsave(here("outputs", "bt_disc.png"), width = 10, height = 10)

terms2plot_sep(latino_pre_disc_bt, asian_pre_disc_bt, "Discrimination", "Pre-1976") + terms2plot_sep(latino_post_disc_bt, asian_post_disc_bt, "Discrimination", "Post-1976")

ggsave(here("outputs", "bt_disc_sep.png"), width = 10, height = 10)
```

```{r}
terms2plot(latino_pre_black_bt, asian_pre_black_bt, "Black", "Pre-1976") + terms2plot(latino_post_black_bt, asian_post_black_bt, "Black", "Post-1976")

ggsave(here("outputs", "bt_black.png"), width = 10, height = 10)

terms2plot_sep(latino_pre_black_bt, asian_pre_black_bt, "Black", "Pre-1976") + terms2plot_sep(latino_post_black_bt, asian_post_black_bt, "Black", "Post-1976")

ggsave(here("outputs", "bt_black_sep.png"), width = 10, height = 10)
```

```{r}
terms2plot(latino_pre_compared_bt, asian_pre_compared_bt, "Compared", "Pre-1976") + terms2plot(latino_post_compared_bt, asian_post_compared_bt, "Compared", "Post-1976")

ggsave(here("outputs", "bt_compared.png"), width = 10, height = 10)

terms2plot_sep(latino_pre_compared_bt, asian_pre_compared_bt, "Compared", "Pre-1976") + terms2plot_sep(latino_post_compared_bt, asian_post_compared_bt, "Compared", "Post-1976")

ggsave(here("outputs", "bt_compared_sep.png"), width = 10, height = 10)
```

```{r}
terms2plot(latino_pre_compared_bt, asian_pre_compared_bt, "Compared", "Pre-1976") + terms2plot(latino_post_compared_bt, asian_post_compared_bt, "Compared", "Post-1976")

ggsave(here("outputs", "bt_compared.png"), width = 10, height = 10)

terms2plot_sep(latino_pre_compared_bt, asian_pre_compared_bt, "Compared", "Pre-1976") + terms2plot_sep(latino_post_compared_bt, asian_post_compared_bt, "Compared", "Post-1976")

ggsave(here("outputs", "bt_compared_sep.png"), width = 10, height = 10)
```

### Contrasting 

```{r}
nns_black <- (con2nplot(subset(corpus, year < 1976), c("black", "african_american"), local_glove, local_transform) + labs(title = "Pre-1976", subtitle = "Keyword: Black")) +

(con2nplot(subset(corpus, year >= 1976), c("black", "african_american"), local_glove, local_transform) + labs(title = "Post-1976", subtitle = "Keyword: Black"))

nns_black 
ggsave(here("outputs", "black_contrast.png"),
       width = 20, height = 15
       )
```

```{r}
nns_disc <- (con2nplot(subset(corpus, year < 1976), "discrimination", local_glove, local_transform) + labs(title = "Pre-1976", subtitle = "Keyword: Discrimination")) +

(con2nplot(subset(corpus, year >= 1976), "discrimination", local_glove, local_transform) + labs(title = "Post-1976", subtitle = "Keyword: Discrimination"))

nns_disc
ggsave(here("outputs", "disc_contrast.png"),
       width = 20, height = 15
       )
```

```{r}
nns_compared <- (con2nplot(subset(corpus, year < 1976), "compared", local_glove, local_transform) + labs(title = "Pre-1976", subtitle = "Keyword: Compared")) +

(con2nplot(subset(corpus, year >= 1976), "compared", local_glove, local_transform) + labs(title = "Post-1976", subtitle = "Keyword: Compared"))

nns_compared
ggsave(here("outputs", "compared_contrast.png"),
       width = 20, height = 15
       )
```

```{r}
nns_disc <- (con2nplot(subset(corpus, year < 1976), "discrimination", local_glove, local_transform) + labs(title = "Pre-1976", subtitle = "Keyword: Discrimination")) +

(con2nplot(subset(corpus, year >= 1976), "discrimination", local_glove, local_transform) + labs(title = "Post-1976", subtitle = "Keyword: Discrimination"))

nns_disc
ggsave(here("outputs", "disc_contrast.png"),
       width = 20, height = 15
       )
```

```{r}
nns_federal <- (con2nplot(subset(corpus, year < 1976), "federal", local_glove, local_transform) + labs(title = "Pre-1976", subtitle = "Keyword: Federal")) +

(con2nplot(subset(corpus, year >= 1976), "federal", local_glove, local_transform) + labs(title = "Post-1976", subtitle = "Keyword: Federal"))

nns_federal
ggsave(here("outputs", "disc_federal.png"),
       width = 20, height = 15
       )
```

## Example texts 

```{r}
latino_pre_black_ex <- get_examples(1, 1, c("black", "african_american", "negro"), 20)
asian_pre_black_ex <- get_examples(0, 1, c("black", "african_american", "negro"), 20)

latino_post_black_ex <- get_examples(1, 0, c("black", "african_american", "negro"), 20)
asian_post_black_ex <- get_examples(0, 0, c("black", "african_american", "negro"), 20)

latino_pre_disc_ex <- get_examples(1, 1, "discrimination", 20)
asian_pre_disc_ex <- get_examples(0, 1, "discrimination", 20)

latino_post_disc_ex <- get_examples(1, 0, "discrimination", 20)
asian_post_disc_ex <- get_examples(0, 0, "discrimination", 20)

asian_pre_black_ex
```
```